export default {
  INIT: 'INIT',
  START: 'START',
  PAUSE: 'PAUSE',
  RESUME: 'RESUME',
  DROP_FRUIT: 'DROP_FRUIT',
  SNAKE_MOVE: 'SNAKE_MOVE',
  UPDATE: 'UPDATE',
  EAT: 'EAT',
  GAME_OVER: 'GAME_OVER',
};
